# Generated by Django 5.0.6 on 2024-08-07 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_name_category_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
    ]
